apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    {{- include "floriapp-mongodb.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    {{- include "floriapp-mongodb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
