apiVersion: v2
name: floriapp-mongodb
description: Install Mongodb configured as a statefulset for use with a flori.app application in kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.7

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "4.4.6"

#appVersion: "4.2"
#db.adminCommand({getParameter: 1, featureCompatibilityVersion: 1})
#db.adminCommand( { setFeatureCompatibilityVersion: "4.2" } )
#db.adminCommand( { setFeatureCompatibilityVersion: "4.4" } )
