
config:
  environment: "live"
  
  connectionstring: "mongodb://mongo-0.mongodb.floriapp.svc.cluster.local:27017"
  database: "floriapp"

  mailMethod: "Smtp"
  mailDirectory: "/app/pickup"
  mailHostname: "mail.lakerfield.net"
  mailTcpport: "25"
  mailUsername: "floriapp@lakerfield.net"
  mailPassword: "..."
  mailFrom: "noreply@floriapp.nl"
  mailFromname: "flori.app"
  mailBcc: "archive@floriapp.nl"

  coderingUrl: "http://deel.ml/code"
  coderingUsername: "michael"
  coderingPassword: "..."
  hostedBehindProxy: "true"
  knownNetworks: "10.22.0.0/16"
  knownProxies: "10.22.0.0"

  networkProxyUrl: "https://proxy1.lakerfield.net"
  networkProxyKey: "..."

  replicas:
    floriappApi: "1"
    floriappMail: "1"
    floriappPhoto: "1"
    floriappServer: "0"
    floriappWeb: "0"

  memoryRequests:
    floriappApi: "1Gi"
    floriappMail: "128Mi"
    floriappPhoto: "128Mi"
    floriappServer: "1Gi"
    floriappWeb: "128Mi"

  memoryLimits:
    floriappApi: "4Gi"
    floriappMail: "512Mi"
    floriappPhoto: "2Gi"
    floriappServer: "4Gi"
    floriappWeb: "1Gi"

  app:
    floriapp:
      agent: "CotradrAalsmeer"
      hostnameForGln: "vmp.flori.app"
      photoThumbUrl: "https://photo.flori.app/"
      clusterIpApi: "10.23.10.11"
      clusterIpPhoto: "10.23.10.201"
      clusterIpWeb: "10.23.10.1"
