apiVersion: v1
kind: ConfigMap
metadata:
  name: config-00-base
data:
  00-base.ini: |
    environment={{ .Values.config.environment }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-10-database
data:
  10-database.ini: |
    [storage]
    mode=ConnectionString
    connectionstring={{ .Values.config.connectionstring }}
    database={{ .Values.config.database }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-20-mail
data:
  20-mail.ini: |
    [mail]
    method={{ .Values.config.mailMethod }}

    [mail:pickup]
    directory={{ .Values.config.mailDirectory }}

    [mail:smtp-server]
    hostname={{ .Values.config.mailHostname }}
    tcpport={{ .Values.config.mailTcpport }}
    username={{ .Values.config.mailUsername }}
    password={{ .Values.config.mailPassword }}

    [mail:address]
    from={{ .Values.config.mailFrom }}
    fromname={{ .Values.config.mailFromname }}
    from-allow-use-of-mailbox-address=true
    bcc={{ .Values.config.mailBcc }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-30-data-floriapp
data:
  30-data.ini: |
    [data]
    auction-transaction-direct-send-ekt={{ .Values.config.auctionTransactionDirectSendEkt }}
    auction-transaction-direct-place-order={{ .Values.config.auctionTransactionDirectPlaceOrder }}
    codering-url={{ .Values.config.coderingUrl }}
    codering-username={{ .Values.config.coderingUsername }}
    codering-password={{ .Values.config.coderingPassword }}
    domain-name-api={{ .Values.config.app.floriapp.domainNameApi }}
    domain-name-web={{ .Values.config.app.floriapp.domainNameWeb }}
    hosted-behind-proxy={{ .Values.config.hostedBehindProxy }}
    kosmos-url={{ .Values.config.kosmosUrl }}
    kosmos-username={{ .Values.config.kosmosUsername }}
    kosmos-password={{ .Values.config.kosmosPassword }}
    kosmos-auction-cluster-id={{ .Values.config.kosmosAuctionClusterId }}
    kosmos-new-user-mail={{ .Values.config.kosmosNewUserMail }}
    known-proxies={{ .Values.config.knownProxies }}
    photo-thumb-url={{ .Values.config.app.floriapp.photoThumbUrl }}
    initial-network-url={{ .Values.config.initialNetworkUrl }}
    vmp-agent={{ .Values.config.app.floriapp.agent }}
    vmp-hostname-for-gln={{ .Values.config.app.floriapp.hostnameForGln }}

    [services]
    etrade=true
    maintenance-active=false
    operation-processing=true
    smtp-mailer=true

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-30-data-vmp4all
data:
  30-data.ini: |
    [data]
    codering-url={{ .Values.config.coderingUrl }}
    codering-username={{ .Values.config.coderingUsername }}
    codering-password={{ .Values.config.coderingPassword }}
    hosted-behind-proxy={{ .Values.config.hostedBehindProxy }}
    known-proxies={{ .Values.config.knownProxies }}
    photo-thumb-url={{ .Values.config.app.vmp4all.photoThumbUrl }}
    vmp-agent={{ .Values.config.app.vmp4all.agent }}
    vmp-hostname-for-gln={{ .Values.config.app.vmp4all.hostnameForGln }}

    [services]
    etrade=true
    maintenance-active=false
    operation-processing=true
    smtp-mailer=true

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-35-hosting
data:
  35-hosting.ini: |
    [hosting]
    hosted-behind-proxy={{ .Values.config.hostedBehindProxy }}
    known-networks={{ .Values.config.knownNetworks }}
    known-proxies={{ .Values.config.knownProxies }}
    
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-40-network
data:
  40-network.ini: |
    [network:node]
    auto-configure=true
    auto-create=false
    configure-tls=false
    #hostname= #(default)
    #domain=  #(default from proxy)
    proxy-url={{ .Values.config.networkProxyUrl }}
    proxy-key={{ .Values.config.networkProxyKey }}
    
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-40-network-tls
data:
  40-network.ini: |
    [network:node]
    auto-configure=true
    auto-create=true
    configure-tls=true
    #hostname= #(default)
    #domain=  #(default from proxy)
    proxy-url={{ .Values.config.networkProxyUrl }}
    proxy-key={{ .Values.config.networkProxyKey }}
    
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-45-network-server
data:
  50-network-server.ini: |
    [network:server]
    enabled=true
    
---

