apiVersion: v1
kind: Service
metadata:
  name: floriapp-server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
  selector:
    {{- include "floriapp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: floriapp-server
  clusterIP: "{{ .Values.config.app.floriapp.clusterIpServer }}"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: floriapp-server
  labels:
    {{- include "floriapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: floriapp-server
spec:
  replicas: {{ .Values.config.replicas.floriappServer }}
  selector:
    matchLabels:
      {{- include "floriapp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: floriapp-server
  serviceName: floriapp-server
  template:
    metadata:
      labels:
        {{- include "floriapp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: floriapp-server
    spec:
      containers:
      - name: floriapp-server
        image: "{{ .Values.image.repository }}/floriapp-server:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        resources:
          limits:
            memory: {{ .Values.config.memoryLimits.floriappServer }}
          requests:
            memory: {{ .Values.config.memoryRequests.floriappServer }}
        volumeMounts:
        - name: floriapp-server-config-volume
          mountPath: /app/config
          readOnly: true
      imagePullSecrets:
      - name: acr-lakerfield
      volumes:
      - name: floriapp-server-config-volume
        projected:
          sources:
          - configMap:
              name: config-10-application
          - configMap:
              name: config-20-hosting
          - configMap:
              name: config-30-network
