name: Horti-ID build completed
on:
  repository_dispatch:
    types: [horti-id-build-event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # other steps
    - name: Edit chart version
      run: |
        sed -i '19s/.*/version: 1.${{ github.event.client_payload.build }}.0/' charts/horti-id/Chart.yaml
        sed -i '25s/.*/appVersion: "${{ github.event.client_payload.build }}"/' charts/horti-id/Chart.yaml
    - name: git commit
      run: |
        git config user.email "lakerfield@gmail.com"
        git config user.name "Michael Lakerveld"
        git add .
        git commit -m "Update horti-id chart to version ${{ github.event.client_payload.build }}"
        git push https://${{secrets.PAT_FOR_COMMIT_TRIGGER}}@github.com/floriapp/helm.git HEAD:main
