name: Horti-ID build completed
on:
  repository_dispatch:
    types: [horti-id-build-event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # other steps
    - name: Edit chart version
      run: |
        sed -i '19s/.*/version: 1.467.1/' charts/horti-id/Chart.yaml
    - name: git commit
      run: |
        git add .
        git commit -m "Update from Workflow"
        git push
